### ISSUE TITLE
add https://github.com/all-contributors/all-contributors

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/API-REST-Documentation-Generator#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aradkdj** [comment]
@all-contributors please add @CharlyJazz for bugs

**Comment by aradkdj** [comment]
@all-contributors add @CharlyJazz for documentation, ideas and code

**Comment by aradkdj** [comment]
@all-contributors please add @rich-97 for code

**Comment by aradkdj** [comment]
@all-contributors please add @aradkdj for code, documentation, and reviews
